### ISSUE TITLE
Name our Project

### ISSUE THREAD

**Issue by djphan** [cntnboys/cmput410-project#4]
Got to start somewhere

**Comment by cntnboys** [comment]
john was finding a name, i can look too

**Comment by gptrinh** [comment]
i called the heroku link410 so if we want to be lazy we can call it Link lol but if not it's very easy to rename so just let me know if you guys have suggestions =P

**Comment by cntnboys** [comment]
http://www.panabee.com/ . Find a name here lol. Ill try and make a good one

**Comment by gptrinh** [comment]
FriendZone was the funniest one I could think of lol

**Comment by djphan** [comment]
Thought Pop
Thought Bubble
Blog Bubble
my2cents

**Comment by djphan** [comment]
2centstodaymillionstomorrow.clickhere :)

**Comment by cntnboys** [comment]
Name for our website? 

Thought Bubble is fine with me 

Any ideas for a logo???? Bubbles? with question marks???

**Comment by gptrinh** [comment]
Name with bubbles or something sounds good to me or something like http://www.clipartbest.com/cliparts/pi5/G4o/pi5G4oXiB.jpeg with "Thought Bubble" inside? or even by itself as a logo

**Comment by maddoxmyco** [comment]
bubble is good, i can't think of anything better

**Comment by chunhanlee** [comment]
Yea that sounds good to me

**Comment by cntnboys** [comment]
Look at our intro page, I have a good thought bubble logo in top left corner of intro page, Ill add a question mark in their , but i think it looks good as the logo.

**Comment by gptrinh** [comment]
have you added the images to the static folder? I don't see them in there at the moment and when I ran it on heroku I don't see the images either http://thoughtbubble.herokuapp.com/

**Comment by cntnboys** [comment]
They are in author/static/images

**Comment by gptrinh** [comment]
https://github.com/cntnboys/cmput410-project/tree/master/author/static/images right? I only see cat and the planet still.

**Comment by cntnboys** [comment]
cat and planet should be gone someone overwriting the pages

**Comment by cntnboys** [comment]
one sec i don think they got added

**Comment by cntnboys** [comment]
ok i added them in sorry

**Comment by gptrinh** [comment]
no problem, It looks great. I like the logo. 

The current version is on thought-bubble.herokuapp.com now by the way if anyone was curious

**Comment by cntnboys** [comment]
Thought-bubble
